import '../lib/src/models/models.dart';

/* 
SELECT ...
FROM ...
WHERE ...
GROUP BY ...
HAVING ...
ORDER BY ...
LIMIT ...
OFFSET ...

UPDATE table
SET column1 = value1
WHERE ...
ORDER BY ...
LIMIT ...

DELETE FROM table
WHERE ...
ORDER BY ...
LIMIT ...
 */

void main() {
  // final sql = Sql.select("test").where(SqlFilter("test1", isEqualTo: 0)).orderBy([
  //   OrderBy(["test2", "test3"]),
  //   OrderBy(["test4"], Order.desc)
  // ]);
  final sql = Sql.insert("table", [{"test1": "value1"}, {"test1": "value2"}]);
  print(sql.build());
}
