import '../lib/src/models/models.dart';

/* 
SELECT ...
FROM ...
WHERE ...
GROUP BY ...
HAVING ...
ORDER BY ...
LIMIT ...
OFFSET ...

UPDATE table
SET column1 = value1
WHERE ...
ORDER BY ...
LIMIT ...

DELETE FROM table
WHERE ...
ORDER BY ...
LIMIT ...
 */

void main() {
  final order = OrderBy.all([
    OrderBy("column1"),
    OrderBy.DESC(["column2", "column3"]),
    OrderBy("column4")
  ]);

  final select = Sql.select("table")
      .where(SqlFilter("column1", isBetween: [1, 18]))
      .orderBy(order)
      .limit(20)
      .offset(10);
  print(select.build());
}
