name: sql_builder
description: A simple Dart wrapper for building SQL queries with chain-able methods
version: 1.0.0

environment: 
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^0.1.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

example:
  - name: "Example"
    path: example/main.dart